"""
class NYT  
"""
class NYT:
    def __init__(self. *args):
        ...
    def built_segments_nyt(self):
        def my_fun():
            ...
        ...

    def built_root_nyt(self):
        ...

    def place_stars_on_segments_nyt(self):
        ...